### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AGENTISNUM1**
Idk, I was bored so I added some stuff. Feel free to edit it!

### CODE REVIEW

**Comment by AGENTISNUM1** [comment]
Ima go edit the phobos main menu, idk why I did this but here :)

Love ur archive btw.

**Comment by Smug2f** [comment]
For real i don't promote the use of paid client, i just find it , bad , i do not say im against it as , it offer some great features that some dont have , but i find it bad to make money on top of notch and his team , no hate to the cheating team to , you can pay if you find it worth it ..

**Comment by AGENTISNUM1** [comment]
Np! if u want, i can remove the paid section!

**Review by AGENTISNUM1 — COMMENTED** [review]
Either i did smth wrong, or the paid section is gone

**Pull request merged**
